<?php

/**
 * Implementation of hook_init().
 */
function riat_init() {
  module_load_include('inc', 'riat', 'includes/riat.api');
}

/**
 * Implementation of hook_views_api().
 */
function riat_views_api() {
  return array(
    'api' => 2,
    'path' => drupal_get_path('module', 'riat') . '/includes',
  );
}

/**
 * Implementation of hook_ctools_plugin_directory().
 */
function riat_ctools_plugin_directory($module, $plugin) {
  if ($module == 'riat' || $module == 'ctools' || $module == 'context_admin') {
    return 'plugins/' . $plugin;
  }
}
