<?php

/**
 * Implementation of hook_init().
 */
function riat_init() {
  module_load_include('inc', 'riat', 'includes/riat.api');
}

/**
 * Implementation of hook_views_api().
 */
function riat_views_api() {
  return array(
    'api' => 2,
    'path' => drupal_get_path('module', 'riat') . '/includes',
  );
}

/**
 * Implementation of hook_ctools_plugin_directory().
 */
function riat_ctools_plugin_directory($module, $plugin) {
  if ($module == 'riat' || $module == 'ctools' || $module == 'context_admin') {
    return 'plugins/' . $plugin;
  }
}

/**
 * Implementation of hook_features_export().
 */
function riat_tree_definition_features_export($data, &$export, $module_name = "") {
  return ctools_component_features_export('riat_tree_definition', $data, $export, $module_name);
}

/**
 * Implementation of hook_features_export_render() for both the
 * riat_definition and riat_tree_definition components.
 */
function riat_definition_features_export_render($module, $data) {
  return ctools_component_features_export_render('riat_definition', $module, $data);
}

function riat_tree_definition_features_export_render($module, $data) {
  drupal_set_message('<pre>'. print_r($module, TRUE) .'</pre>');
  drupal_set_message('<pre>'. print_r($data, TRUE) .'</pre>');
  return ctools_component_features_export_render('riat_tree_definition', $module, $data);
}
